name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's
  launcher icon.
version: 0.11.0
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons
repository: https://github.com/fluttercommunity/flutter_launcher_icons/
issue_tracker: https://github.com/fluttercommunity/flutter_launcher_icons/issues

dependencies:
  args: ^2.4.0
  checked_yaml: ^2.0.2
  cli_util: ^0.3.5
  image: ^4.0.15
  json_annotation: ^4.8.0 
  yaml: ^3.1.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  # allows us to get version number from pubspec yaml which we can pass to Sentry
  # https://pub.dev/packages/build_version
  build_version: ^2.1.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2
